### ISSUE TITLE
Checkboxes [Checked] Binding

### ISSUE THREAD

**Issue by Rodolfo-XDR** [selemxmn/ngx-print#104]
**Describe the bug**
When I bind a HTML Element that has a checkbox with a 'checked' binding in true, it shows as not checked.

**To Reproduce**
Print a HTML Element with a Checkbox Input and bind `checked` and it will show as not checked. If you hardcode `checked` it will show with no issue.

**Expected behavior**
When binding `checked`  property as true, it should show it aswell.

**Screenshots**
![image](https://user-images.githubusercontent.com/49254245/99128783-59357400-25d1-11eb-858e-01cb8cc7afca.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Lastest

**Additional context**
If you notice on the screenshot, `disabled` property does bind.

**Comment by broem** [comment]
v1.2.0 closed
