### ISSUE TITLE
Not able to print once again if we close the window the first time

### ISSUE THREAD

**Issue by shinoyj1208** [selemxmn/ngx-print#111]
Not able to print one again if we close the window the first time,

If we click on the print the popup will come. if we close the window through the x button on top of the bar,
After that if we again try to print it is not working. The whole application gets stuck. (Chrome Browser)

[https://stackblitz.com/edit/demo-ngx-print](https://stackblitz.com/edit/demo-ngx-print)

**Comment by broem** [comment]
This looks like your using a very old version of ngx-print. Updating to the most recent 1.2.0-beta.6 version works fine.

**Comment by shinoyj1208** [comment]
after changing to the latest version still not working, [https://stackblitz.com/edit/demo-ngx-print-x?file=package.json](https://stackblitz.com/edit/demo-ngx-print-x?file=package.json)

**Comment by shinoy-jose** [comment]
@broem  Some help here... its closed. should I open it as a new issue again..

**Comment by broem** [comment]
What chrome version are you using? What OS? Your stackblitz works as intended for me.

**Comment by shinoy-jose** [comment]
Chrome version is 89 and OS is windows 8. Could it be because of OS

**Comment by thanhhai1998** [comment]
same issue, if i click button cancel, it's work, but if i click button X (close), it close but then  The whole application gets stuck and i cant reload page

**Comment by broem** [comment]
That's definitely a possibility, maybe look at [this](https://superuser.com/questions/944441/web-page-crashes-when-attempting-to-print-on-google-chrome ) . 

I don't have an easy way of testing functionality on win8.

**Comment by shinoy-jose** [comment]
I tried clearing the %localappdata%\Google Still facing the issue

**Comment by heloisarsantos** [comment]
também estou enfrentando esse problema com a ngx-print
Clico no X, e a pagina trava.
Se clicar em cancelar, funciona perfeitamente.

**Comment by broem** [comment]
What OS are you using @heloisarsantos

**Comment by heloisarsantos** [comment]
> Qual sistema operacional você está usando @heloisarsantos

Estou usando o Windows 10. E pra navegador, o Chrome.

**Comment by sohaibex** [comment]
same issue here when i click in the cancel button it work but when i click in close X the whole app freeze and i can't access to anything i tried it in google chrome and microsoft edge

**Comment by broem** [comment]
Yep, so it looks like there was a recent update for chrome (edge too) that messed up how window callbacks are functioning with the print pop-up dialog. I wasn't seeing this error until I updated to most recent chrome. Currently I don't have a solution.

**Comment by broem** [comment]
I cannot fix it, I've opened a ticket with chromium as have several others relating to this same issue. The problem lays in the browser, once that team has triaged and fixed it the issue should be resolved. Apologies for any inconveniences.

**Comment by sohaibex** [comment]
> Same issue here, can you fix this please?
i did an alternative solution i creat a component that has the div that i want to print then  i hide all css in the page except the div that i want to print plus i make max with 100% then i make window.print()

**Comment by broem** [comment]
Looks like the most recent version of Chrome has fixed the issue, at least as of 90.0.4430.93 (Official Build). It looks like Edge hasn't rolled out the fix as of yet so I will leave this issue open for now. 

Thanks guys

**Comment by broem** [comment]
Seems to now be working with most recent version of Edge now.
