### ISSUE TITLE
can inactive tab data be printed ? 

### ISSUE THREAD

**Issue by NIKITA-2710** [selemxmn/ngx-print#112]
I have multiple tabs in my page. Tab content are in child components and are hidden if the tab is inactive, I have print button in parent component. When I click on print, only the active tab content is printed.

I want to print the content of all the tabs irrespective of whether its active or not , in different pages . Is it possible to achieve ?

@broem  Can you please help.

**Comment by broem** [comment]
If the content is not on the DOM then the directive wouldn't be able to see it. Maybe you can reveal the hidden content in the tabs somehow and then print? 

Ngx-print has no other way of printing things if its not visible.

**Comment by NIKITA-2710** [comment]
@borem Thanks 

I think I will work around using media css .
