### ISSUE TITLE
Issue while doing build

### ISSUE THREAD

**Issue by umamaheshbhamidipati** [selemxmn/ngx-print#114]
Hi Author,

getting issue while doing a build, getting error near import of this module in another lazy loaded module. Please check once

error TS2307: Cannot find module 'ngx-print'. Build step 'Execute shell' marked build as failure

**Comment by samizarraa** [comment]
Same issue

**Comment by marosrojis** [comment]
Same issue, if I use `1.2.0-beta.6` everythink works without any problem.

**Comment by broem** [comment]
Try bumping to version ``1.2.1`` , I think the ``1.2.0`` version had an issue
