### ISSUE TITLE
How to call ngx-print from a function

### ISSUE THREAD

**Issue by thelionleo** [selemxmn/ngx-print#119]
I would like to call ngx-print from a function in .ts file

I have a button that calls the server, when data gathering is complete, then, print.

How do it do this?

**Comment by Skuriles** [comment]
Use a template reference in HTML "#print". Add a click event on any other element and hide the button where the template reference is set => invisible button, so you can use any element you want to trigger the print, as only button works.

`<div (click)="triggerPrint();">
    <span>Print</span>
  </div>
<button #print printTitle="report" printSectionId="content-section" ngxPrint hidden="true" [useExistingCss]="true"
 ></button>`

In TS file use the ViewChild to add the template reference and use it in your triggerPrint method

`
@ViewChild("print") print!: ElementRef;

public triggerPrint(): void {   
      this.print.nativeElement.click();
  }`

**Comment by broem** [comment]
Does that work for you @thelionleo ?

**Comment by belicekm** [comment]
This solution works flawlessly.
It will also work when the the "content-section" is set to display: none.
