### ISSUE TITLE
Does not work on mobile Chrome

### ISSUE THREAD

**Issue by dopinder100** [selemxmn/ngx-print#120]
This is a great component, and works really well on desktops. But, I need to use this functionality on mobile browsers.

On mobile browsers, such as Chrome, it doesn't seem to work. It will just open up a window and says "There was a problem printing the page. Please try again".

Anyone has any solution?

Thanks.

**Comment by jmijmi** [comment]
Important functionality for me too, any solution?

**Comment by dopinder100** [comment]
No solution. I ended up generating the PDF file on the server.

**Comment by sdecianu** [comment]
I also have the same issue :(

**Comment by calldeludo** [comment]
Any update? I need this functionality....

**Comment by Kijacode** [comment]
any progress in this issue @sdecianu @jmijmi @calldeludo @davemecha @dopinder100 ,@selemxmn  ....

**Comment by calldeludo** [comment]
Hi everyone... since no one shared a solution, i refused to use this library because this problem seems that no body will fix it. The bug is just easy, chrome on mobile just close the tab before print thats why ngx-print fails, so i decided to do something similar

With this approach i just control if the device is a mobile or desktop, if it a mobile just remove window.close onload body.

```
  printContents = document.getElementById('print-section').innerHTML;
    popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
    popupWin.document.open();
    if (this.deviceService.isDesktop()) {
      popupWin.document.write(`
      <html>
        <head>
          <title>${titulo}</title>
//ADD BOOTSTRAP IF YOU ARE USING IT
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
          <style>
          //........Customized style.......
          ...
          </style>
        </head>
    <body onload="window.print();window.close()">${printContents}</body>
      </html>`
      );
      popupWin.document.close();
    } else { //REMOVE window.close() if the device is a mobile.
      popupWin.document.write(`
      <html>
        <head>
          <title>Print tab</title>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
          <style>
          //........Customized style.......
         ....
          </style>
        </head>
        <body onload="window.print()">${printContents}</body>
      </html>`
      );
      popupWin.document.close();
    }
  }
```
I hope it helps someone, for me is working perfectly!

**Comment by Kijacode** [comment]
> Hi everyone... since no one shared a solution, i refused to use this library because this problem seems that no body will fix it. The bug is just easy, chrome on mobile just close the tab before print thats why ngx-print fails, so i decided to do something similar
> 
> With this approach i just control if the device is a mobile or desktop, if it is a mobile just remove window.close onload body.
> 
> ```
>   printContents = document.getElementById('print-section').innerHTML;
>     popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
>     popupWin.document.open();
>     if (this.deviceService.isDesktop()) {
>       popupWin.document.write(`
>       <html>
>         <head>
>           <title>${titulo}</title>
> //ADD BOOTSTRAP IF YOU ARE USING IT
>           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
>           <style>
>           //........Customized style.......
>           ...
>           </style>
>         </head>
>     <body onload="window.print();window.close()">${printContents}</body>
>       </html>`
>       );
>       popupWin.document.close();
>     } else { //REMOVE window.close() if the device is a mobile.
>       popupWin.document.write(`
>       <html>
>         <head>
>           <title>Print tab</title>
>           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
>           <style>
>           //........Customized style.......
>          ....
>           </style>
>         </head>
>         <body onload="window.print()">${printContents}</body>
>       </html>`
>       );
>       popupWin.document.close();
>     }
>   }
> ```
> 
> I hope it helps someone, for me is working perfectly!

so boss, with this approach it means you are incoparate it with the package ,,,but you just detect for mobile the tab to not close on chrome ?

**Comment by Kijacode** [comment]
> > Hi everyone... since no one shared a solution, i refused to use this library because this problem seems that no body will fix it. The bug is just easy, chrome on mobile just close the tab before print thats why ngx-print fails, so i decided to do something similar
> > With this approach i just control if the device is a mobile or desktop, if it is a mobile just remove window.close onload body.
> > ```
> >   printContents = document.getElementById('print-section').innerHTML;
> >     popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
> >     popupWin.document.open();
> >     if (this.deviceService.isDesktop()) {
> >       popupWin.document.write(`
> >       <html>
> >         <head>
> >           <title>${titulo}</title>
> > //ADD BOOTSTRAP IF YOU ARE USING IT
> >           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
> >           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
> >           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
> >           <style>
> >           //........Customized style.......
> >           ...
> >           </style>
> >         </head>
> >     <body onload="window.print();window.close()">${printContents}</body>
> >       </html>`
> >       );
> >       popupWin.document.close();
> >     } else { //REMOVE window.close() if the device is a mobile.
> >       popupWin.document.write(`
> >       <html>
> >         <head>
> >           <title>Print tab</title>
> >           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
> >           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
> >           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
> >           <style>
> >           //........Customized style.......
> >          ....
> >           </style>
> >         </head>
> >         <body onload="window.print()">${printContents}</body>
> >       </html>`
> >       );
> >       popupWin.document.close();
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope it helps someone, for me is working perfectly!
> 
> @calldeludo thanks alot ,thats work for me as well ,except (I just use document/window . ,instead of starting with popUpWin) ..I don't know if it could rise any issue in the future r what was the essence of starting with popUpWin ?

**Comment by calldeludo** [comment]
> > @calldeludo thanks alot ,thats work for me as well ,except (I just use document/window . ,instead of starting with popUpWin) ..I don't know if it could rise any issue in the future r what was the essence of starting with popUpWin ?

i think it is all about user experience... in my case is more useful to open it as a popup and then close after print... but using document/window should be the same.

**Comment by sohebcakewalk** [comment]
@calldeludo @Kijacode - Thanks a lot, this works for me too. 

But one issue is that, my page does not contain background color in print preview on mobile device but i get it in desktop.

**Comment by souckmi** [comment]
Hello, @calldeludo thank you very much, that works so nicely.
@sohebcakewalk I am late, but for anyone else, adding 
```
* { color-adjust: exact;
     -webkit-print-color-adjust: exact;}
```
to the <style></style> section solves the problem, at least form me in Chrome and Firefox.

However, the fix for this issue would be so appreciated.

**Comment by abahuus** [comment]
> Hi everyone... since no one shared a solution, i refused to use this library because this problem seems that no body will fix it. The bug is just easy, chrome on mobile just close the tab before print thats why ngx-print fails, so i decided to do something similar
> 
> With this approach i just control if the device is a mobile or desktop, if it is a mobile just remove window.close onload body.
> 
> ```
>   printContents = document.getElementById('print-section').innerHTML;
>     popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
>     popupWin.document.open();
>     if (this.deviceService.isDesktop()) {
>       popupWin.document.write(`
>       <html>
>         <head>
>           <title>${titulo}</title>
> //ADD BOOTSTRAP IF YOU ARE USING IT
>           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
>           <style>
>           //........Customized style.......
>           ...
>           </style>
>         </head>
>     <body onload="window.print();window.close()">${printContents}</body>
>       </html>`
>       );
>       popupWin.document.close();
>     } else { //REMOVE window.close() if the device is a mobile.
>       popupWin.document.write(`
>       <html>
>         <head>
>           <title>Print tab</title>
>           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
>           <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
>           <style>
>           //........Customized style.......
>          ....
>           </style>
>         </head>
>         <body onload="window.print()">${printContents}</body>
>       </html>`
>       );
>       popupWin.document.close();
>     }
>   }
> ```
> 
> I hope it helps someone, for me is working perfectly!

@calldeludo can you help me,  where I have to put the code in my component, I am new to Angular...

**Comment by Kijacode** [comment]
Hello @abahuus , I have document most of the ways to help you to cover this up .
check this blog post [here](https://stealth-timpani-d31.notion.site/The-perspective-of-Download-pdf-Feature-in-Js-Js-Frameworks-Reactjs-Angular-Vue-2089cd8bee344a76b2ebce0b762fc6ba)

**Comment by calldeludo** [comment]
@Kijacode nice post 👍 
@abahuus go to his blog, all is good explained there

Regards

**Comment by abahuus** [comment]
@Kijacode  @calldeludo ... thanks for your kin attention...

**Comment by PRANITHMEESALA** [comment]
Same problem in Reactjs also can you give solution to me.

**Comment by Kijacode** [comment]
> Same problem in Reactjs also can you give solution to me.

Hello @PRANITHMEESALA , please also check this out using the package known as [printjs](https://printjs.crabbly.com/)

**Comment by broem** [comment]
This has been fixed with the [closeWindow] option in #165

**Comment by urvesh-igenerate** [comment]
const newWindow = window.open("", "_blank");
            if (newWindow) {
              newWindow.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Print PDF</title>
    <style>
        /* CSS Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        html, body {
            width: 100%;
            height: 100%;
            overflow: hidden;
        }

        #printButton {
            position: fixed;
            bottom: 10px;
            left: 50px;
            z-index: 9999;
            padding: 10px;
            background: #1F51FF;
            color: #fff;
            cursor: pointer;
        }

        #pdfContainer {
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        @media print {
            #printButton {
                display: none;
            }

            html, body, #pdfContainer {
                margin: 0 !important;
                padding: 0 !important;
                width: 100%;
                height: 100%;
                overflow: hidden !important;
            }

            #pdfContainer canvas {
                width: 100% !important;
                height: 100% !important;
            }
        }
    </style>
</head>
<body>
<button id="printButton">Print</button>
<div id="pdfContainer"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
<script>
    document.getElementById('printButton').addEventListener('click', function() {
        window.print();
    });

    // Initialize PDF.js
    const pdfContainer = document.getElementById('pdfContainer');
    const loadingTask = pdfjsLib.getDocument("${iframeUrl}"); // Use the blob URL created for the PDF
    loadingTask.promise.then(function(pdf) {
        // Fetch the first page
        pdf.getPage(1).then(function(page) {
            const scale = 2; // Adjust scale to ensure full-page fit
            const viewport = page.getViewport({ scale: scale });
            const canvas = document.createElement('canvas');
            const context = canvas.getContext('2d');
            canvas.height = viewport.height;
            canvas.width = viewport.width;
            const renderContext = {
                canvasContext: context,
                viewport: viewport
            };
            page.render(renderContext).promise.then(function() {
                pdfContainer.innerHTML = '';
                pdfContainer.appendChild(canvas);
                // Adjust canvas to fit the container
                canvas.style.width = '100%';
                canvas.style.height = '100%';
            });
        });
    });
</script>
</body>
</html>`);
              newWindow.document.close();
            } else {
              alert("Please allow popups for this website");
            }

**Comment by URVESH1121** [comment]
```
export const printPdf = (() => {
  const isFirefox = /Gecko\/\d/.test(navigator.userAgent);
  const isAndroid = /Android/.test(navigator.userAgent);
  const firefoxDelay = 1000;
  let iframe;

  return function (url) {
    if (iframe) {
      iframe.parentNode.removeChild(iframe);
    }

    iframe = document.createElement("iframe");
    iframe.style.cssText =
      "width: 1px; height: 100px; position: fixed; left: 0; top: 0; opacity: 0; border-width: 0; margin: 0; padding: 0";

    const xhr = new XMLHttpRequest();
    try {
      xhr.responseType = "arraybuffer";
    } catch (e) {
      window.open(url, "_blank");
      return;
    }

    xhr.addEventListener("load", function () {
      if (xhr.status === 200 || xhr.status === 201) {
        const pdfBlob = new Blob([xhr.response], { type: "application/pdf" });
        const iframeUrl = URL.createObjectURL(pdfBlob);
        iframe.src = iframeUrl;

        iframe.addEventListener("load", function () {
          const openPrintPreview = () => {
            try {
              iframe.focus();
              iframe.contentWindow.print();
            } catch (error) {
              console.error("Print preview failed: " + error, error);
            } finally {
              URL.revokeObjectURL(iframeUrl);
            }
          };

          if (isFirefox) {
            window.setTimeout(openPrintPreview, firefoxDelay);
          } else if (isAndroid) {
            const newWindow = window.open("", "_blank");
            if (newWindow) {
              newWindow.document.write(`
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Print PDF</title>
                    <style>
                        /* CSS Reset */
                        * {
                            margin: 0;
                            padding: 0;
                            box-sizing: border-box;
                        }
                
                        html, body {
                            width: 100%;
                            height: 100%;
                            overflow: hidden;
                        }
                
                        #printButton {
                            position: fixed;
                            bottom: 10px;
                            left: 50px;
                            z-index: 9999;
                            padding: 10px;
                            background: #1F51FF;
                            color: #fff;
                            cursor: pointer;
                        }
                
                        #pdfContainer {
                            width: 100%;
                            height: 100%;
                            display: flex;
                            align-items: center;
                            justify-content: center;
                        }
                
                        @media print {
                            #printButton {
                                display: none;
                            }
                
                            html, body, #pdfContainer {
                                margin: 0 !important;
                                padding: 0 !important;
                                width: 100%;
                                height: 100%;
                                overflow: hidden !important;
                            }
                
                            #pdfContainer canvas {
                                width: 100% !important;
                                height: 100% !important;
                            }
                        }
                    </style>
                </head>
                <body>
                <button id="printButton">Print</button>
                <div id="pdfContainer"></div>
                
                <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
                <script>
                    document.getElementById('printButton').addEventListener('click', function() {
                        window.print();
                    });
                
                    // Initialize PDF.js
                    const pdfContainer = document.getElementById('pdfContainer');
                    const loadingTask = pdfjsLib.getDocument("${iframeUrl}"); // Use the blob URL created for the PDF
                    loadingTask.promise.then(function(pdf) {
                        // Fetch the first page
                        pdf.getPage(1).then(function(page) {
                            const scale = 2; // Adjust scale to ensure full-page fit
                            const viewport = page.getViewport({ scale: scale });
                            const canvas = document.createElement('canvas');
                            const context = canvas.getContext('2d');
                            canvas.height = viewport.height;
                            canvas.width = viewport.width;
                            const renderContext = {
                                canvasContext: context,
                                viewport: viewport
                            };
                            page.render(renderContext).promise.then(function() {
                                pdfContainer.innerHTML = '';
                                pdfContainer.appendChild(canvas);
                                // Adjust canvas to fit the container
                                canvas.style.width = '100%';
                                canvas.style.height = '100%';
                            });
                        });
                    });
                </script>
                </body>
                </html>
                `);
              newWindow.document.close();
            } else {
              alert("Please allow popups for this website");
            }
          } else {
            openPrintPreview();
          }
        });

        document.body.appendChild(iframe);
      }
    });

    xhr.open("GET", url, true);
    xhr.send();
  };
})();
```
This is the complete function code, compatible with both PC and mobile devices, and all browsers.
