### ISSUE TITLE
Is it possible to avoid the printer selection dialog when calling ngxPrint

### ISSUE THREAD

**Issue by itsbw** [selemxmn/ngx-print#126]
I use ngxPrint in a kiosk-like scenario. 
As soon as the print button is pressed the printer selection dialog pops up.

Is there a way to avoid this behavior and directly print on the standard printer?

**Comment by henimex** [comment]
no one answered this question but I need this too. I will use this print output as a sale summary after the order is completed. It should be directly printer without user action.

**Comment by schmidlindreinhard** [comment]
@selemxmn please can you help us with this issue...???

**Comment by schmidlindreinhard** [comment]
@broem can you see this my friend

**Comment by Core121** [comment]
This is available in the new version by setting [previewOnly]="true"

**Comment by henimex** [comment]
> This is available in the new version by setting [previewOnly]="true"

I will definitely going to use this. thank you for your information
