### ISSUE TITLE
Is there any possibility to set the orientation to landscape?

### ISSUE THREAD

**Issue by mwimmer-bcx** [selemxmn/ngx-print#136]
Is there any possibility to set the orientation to landscape? It would be good, if there would be a possibility to set the orientation. Maybe via parameter but it is up on you.

Is there any way to do it with a workaround right now? Maybe some css @page @media?

Kind regards,
Manuel

**Comment by cliffeby** [comment]
I have the same request, but point out the following.
1.  When I do not apply css using [useExistingCss]="true", the Layout dropdown option (portrait or landscape) is present when trying to print.
2.  My css contains a @media print{@page {size: landscape}} line, but it seems to be ignored by ngx-print.

**Comment by kapik** [comment]
Hey 👋
To do this I combined the two options in this way:

```html
 [printStyle]="{ '@page': { size: 'landscape !important' } }"
 [useExistingCss]="true"
```

**Comment by doccocaubaii** [comment]
Is there a way for the Layout dropdown option to be present, but for me to set a default layout for it?
I mean, I want to set it to landscape A5 by default whenever the print settings pop up, but the user can still change it.
