### ISSUE TITLE
Ivy distribution

### ISSUE THREAD

**Issue by makosaisaac** [selemxmn/ngx-print#142]
When running the project it's saying 

Encourage the library authors to publish an Ivy distribution.

**Comment by profkaygee** [comment]
I hope this can be looked at soon because it breaks any Angular 13 application if used. Will need to remove it from my application for now.

**Comment by Core121** [comment]
There will be an ivy support update within the next few days that will close this issue. 😄

**Comment by Core121** [comment]
New version is out!
