### ISSUE TITLE
ngx-print throw error with angular 14 

### ISSUE THREAD

**Issue by vikastyagi82** [selemxmn/ngx-print#153]
Error: node_modules/ngx-print/lib/ngx-print.directive.d.ts:93:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

93     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPrintDirective, "button[ngxPrint]", never, { "previewOnly": "previewOnly"; "printSectionId": "printSectionId"; "printTitle": "printTitle"; "useExistingCss": "useExistingCss"; "printDelay": "printDelay"; "printStyle": "printStyle"; "styleSheetFile": "styleSheetFile"; }, {}, never, never, false, never>;

**Angular version**
"@angular/cdk": "^14.0.4",
"@angular/common": "^14.0.4",
"@angular/compiler": "^14.0.4",
"@angular/core": "^14.0.4",
"ngx-print": "^1.2.1",
      
**Usage in HTML** 
<button class="btn btn-small"
                        [useExistingCss]="true"
                        ngxPrint>Print</button>

**Comment by Core121** [comment]
Try running `npm i ngx-print@1.2.1`
Looks like you have 1.3.1 installed even if npm is saying it's 1.2.1, the previewOnly tag doesn't exist in 1.2.1 so that's not the version currently installed.

**Comment by vikastyagi82** [comment]
Thanks for reply, clear the NPM cache, and install node modules again and runs the command you suggest and it works.
