### ISSUE TITLE
Error while installing ngx-print @1.2.1 on angular 11.1.2

### ISSUE THREAD

**Issue by NavalAndhyal** [selemxmn/ngx-print#154]
{
  "name": "clientportalweb",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-prod": "node --max_old_space_size=10096 ./node_modules/@angular/cli/bin/ng build --prod",
    "serve-prod": "node serve --configuration=production",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build-environment": "gulp build-environment",
    "build-classvals": "gulp build-classification-values",
    "build-build-result": "gulp build-build-result"
  },
  "private": true,
  "dependencies": {
    "@angular-package/change-detection": "^1.0.0",
    "@angular/animations": "11.1.1",
    "@angular/cdk": "^11.1.1",
    "@angular/common": "11.1.1",
    "@angular/compiler": "11.1.1",
    "@angular/core": "11.1.1",
    "@angular/forms": "11.1.1",
    "@angular/localize": "^11.1.1",
    "@angular/material": "^11.1.1",
    "@angular/material-moment-adapter": "11.1.1",
    "@angular/platform-browser": "11.1.1",
    "@angular/platform-browser-dynamic": "11.1.1",
    "@angular/router": "11.1.1",
    "@azure/msal-angular": "^2.0.0-alpha.6",
    "@azure/msal-browser": "^2.11.2",
    "@microsoft/applicationinsights-web": "^2.1.1",
    "@ng-bootstrap/ng-bootstrap": "^5.0.0",
    "@types/pdfjs-dist": "2.0.1",
    "adal-angular5": "^1.0.36",
    "angular-2-local-storage": "^3.0.1",
    "angular-l10n": "^8.1.2",
    "angular-mydatepicker": "^0.10.3",
    "angular2-signaturepad": "^2.11.0",
    "angular2-text-mask": "^9.0.0",
    "animate.css": "3.5.2",
    "automapper-ts": "^1.9.0",
    "bootstrap": "^4.6.0",
    "chart.js": "^2.8.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "hammer": "0.0.5",
    "intl": "1.2.5",
    "jquery": "^3.4.1",
    "material-design-icons": "3.0.1",
    "moment-timezone": "^0.5.31",
    "mydatepicker": "^9.0.2",
    "ng-busy": "8.0.0",
    "ng-multiselect-dropdown": "^0.2.3",
    "ng2-charts": "^2.4.2",
    "ng2-pdf-viewer": "^6.3.2",
    "ngx-cookie-service": "^3.1.3",
    "ngx-custom-validators": "^11.0.1",
    "ngx-pagination": "^5.0.0",
    "ngx-print": "^1.2.1",
    "open-sans-fontface": "1.4.0",
    "pnotify": "3.0.0",
    "primeng": "^4.0.3",
    "proxy-polyfill": "0.1.6",
    "quill": "^1.3.7",
    "reflect-metadata": "0.1.10",
    "rxjs": "^6.6.7",
    "sass": "^1.32.6",
    "text-mask-addons": "^3.7.1",
    "tslib": "^2.3.0",
    "url": "^0.11.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.2",
    "@angular/cli": "^11.1.2",
    "@angular/compiler-cli": "11.1.1",
    "@types/hammerjs": "^2.0.38",
    "@types/jasmine": "~3.6.0",
    "@types/jquery": "2.0.41",
    "@types/jquery.pnotify": "3.0.33",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^4.14.2",
    "@typescript-eslint/parser": "^4.14.2",
    "codelyzer": "^6.0.0",
    "enhanced-resolve": "3.3.0",
    "eslint": "^7.19.0",
    "eslint-config-google": "^0.14.0",
    "fs-extra": "^3.0.1",
    "gulp": "^4.0.2",
    "gulp-file": "0.4.0",
    "gulp-umd": "2.0.0",
    "handlebars": "^4.5.3",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "nswag": "^13.0.6",
    "protractor": "~7.0.0",
    "pump": "^1.0.2",
    "request": "^2.81.0",
    "ts-node": "~3.0.4",
    "tslint": "~6.1.0",
    "typescript": "4.0.5",
    "upath": "^1.2.0"
  }
}

**Comment by Core121** [comment]
Please include the error as well, I won't be able to help with just your package list

**Comment by NavalAndhyal** [comment]
Getting below error, while doing ng serve.


Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 228:10-19
Can't import the named export 'Directive' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 256:12-24
Can't import the named export 'HostListener' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 235:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 238:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 241:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 244:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 247:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 250:12-17
Can't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 253:12-17
[0mCan't import the named export 'Input' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 292:10-18
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 200:10-28
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 270:10-28
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 202:25-45
Can't import the named export 'ɵɵdefineDirective' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 207:6-19
Can't import the named export 'ɵɵlistener' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 222:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 286:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 194:25-46
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 264:22-43
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 280:22-44
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-print/fesm2015/ngx-print.mjs 272:22-44
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

**Comment by NavalAndhyal** [comment]
Getting this issue, while installing using "npm i ngx-print@1.2.1"

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular/localize@11.2.6
npm ERR! Found: @angular/compiler@11.1.1
npm ERR! node_modules/@angular/compiler
npm ERR!   peer @angular/compiler@"11.1.1" from @angular/compiler-cli@11.1.1
npm ERR!   node_modules/@angular/compiler-cli
npm ERR!     peer @angular/compiler-cli@"^11.0.0 || ^11.1.0-next" from @angular-devkit/build-angular@0.1101.2
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~0.1101.2" from the root project
npm ERR!     peer @angular/compiler-cli@"^11.0.0 || ^11.1.0-next" from @ngtools/webpack@11.1.2
npm ERR!     node_modules/@ngtools/webpack
npm ERR!       @ngtools/webpack@"11.1.2" from @angular-devkit/build-angular@0.1101.2
npm ERR!       node_modules/@angular-devkit/build-angular
npm ERR!         dev @angular-devkit/build-angular@"~0.1101.2" from the root project
npm ERR!     1 more (the root project)
npm ERR!   peer @angular/compiler@"11.1.1" from @angular/platform-browser-dynamic@11.1.1
npm ERR!   node_modules/@angular/platform-browser-dynamic
npm ERR!     @angular/platform-browser-dynamic@"11.1.1" from the root project
npm ERR!   1 more (the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"11.2.6" from @angular/localize@11.2.6
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.1.0-next" from @angular-devkit/build-angular@0.1101.2
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1101.2" from the root project
npm ERR!   @angular/localize@"^11.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/compiler@11.2.6
npm ERR! node_modules/@angular/compiler
npm ERR!   peer @angular/compiler@"11.2.6" from @angular/localize@11.2.6
npm ERR!   node_modules/@angular/localize
npm ERR!     peerOptional @angular/localize@"^11.0.0 || ^11.1.0-next" from @angular-devkit/build-angular@0.1101.2
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~0.1101.2" from the root project
npm ERR!     @angular/localize@"^11.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Naval_Andhyal\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naval_Andhyal\AppData\Local\npm-cache\_logs\2022-12-29T02_29_18_687Z-debug-0.log

**Comment by Core121** [comment]
I would run an ng update and get the latest version of angular 11. Looks like it's looking for 11.2.6 and you have 11.1.1

**Comment by Core121** [comment]
I think there could also be something wrong with your configuration, ngx-print 1.2.1 was built using angular 7 cli so I have a hard time believing it's requiring a certain version of angular 11. Can you zip your repo or post a link here? You could also try installing with --legacy-peer-deps to see if that works but it usually wouldn't be necessary. But I'm not sure what else would be incorrect based on the errors and package.json

**Comment by Core121** [comment]
Try changing your package.json from ngx-print "^1.2.1" to "1.2.1"
