### ISSUE TITLE
Build error with Angular 14.2.9

### ISSUE THREAD

**Issue by nimbusparis** [selemxmn/ngx-print#156]
Unable to build (production or staging) when Angular packages are updated to 14.2.9

Error: node_modules/ngx-print/lib/ngx-print.directive.d.ts:93:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

93     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPrintDirective, "button[ngxPrint]", never, { "previewOnly": "previewOnly"; "printSectionId": "printSectionId"; "printTitle": "printTitle"; "useExistingCss": "useExistingCss"; "printDelay": "printDelay"; "printStyle": "printStyle"; "styleSheetFile": "styleSheetFile"; }, {}, never, never, false, never>;

**Comment by Core121** [comment]
Looks like you're using 1.3.1 which only supports angular 15 and up. Try `npm i ngx-print@1.2.1` for angular 14

**Comment by gorumuchupraveen** [comment]
Facing the same issue with 14.2.0 Version. even for this version also npm i ngx-print@1.2.1 throwing an error.!

**Comment by nimbusparis** [comment]
Ok, I see where was the misstake, I was using ^1.2.1 (from to above) instead of 1.2.1 (exact) and npm install instaled the 1.3.1 version.
