### ISSUE TITLE
Preview mode on older versions

### ISSUE THREAD

**Issue by LordKriegan** [selemxmn/ngx-print#164]
Our project uses an older verison of angular (v13) so naturally I have to use 1.2.1 of your plugin. However, it looks like preview mode is only on 1.3. Is it possible to get preview mode added to 1.2.1 as well?

**Comment by Core121** [comment]
Hey @LordKriegan, while I would like to add this in the old version I don't have a ton of time to complete it nor verify if existing pull requests to fix this issue actually work. I would suggest using the property [printDelay] and setting it to a very high value. That way you can view the css without getting the print dialog.
Example: [printDelay]="9999999999999"
