### ISSUE TITLE
Blank Space After First Page

### ISSUE THREAD

**Issue by SeKutai** [selemxmn/ngx-print#168]
**Describe the bug**
When trying to print some HTML there is a blank space after the end of the first page.

**To Reproduce**
```html
<div class="max-h-128 max-w-screen-md flex flex-col overflow-hidden">

    <div class="flex p-2 w-full justify-center sticky top-0 bg-white">
        <button mat-raised-button [useExistingCss]="true" printSectionId="printarea"
            [printTitle]="ptdData.ptd.udfVenderPONumber" ngxPrint color="primary">
            <mat-icon svgIcon="heroicons_outline:printer"></mat-icon>
            <span class="px-2">Print</span>
        </button>
    </div>

    <ng-container *ngIf="true">
        <div id="printarea">
            <ng-container *ngFor="let a of zeroToOneHundred">
                {{ a }}
                <br>
            </ng-container>
        </div>
    </ng-container>

</div>
```

**Expected behavior**
The start of the second page would normally be at the top of the second page.

**Screenshots**
[numbers.pdf](https://github.com/selemxmn/ngx-print/files/12439389/numbers.pdf)
![image](https://github.com/selemxmn/ngx-print/assets/107933316/61c13fe7-2b89-4507-ab94-f11f412927b8)

**Ngx-Print Version**
ngx-print 1.2.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 116.0.1938.54

**Additional context**
I have found that removing [useExistingCss]="true" gets the second page to start at the top. However, I need the css in order to get the HTML that I actually want to print to show up properly. Also I am using tailwind.

**Comment by Core121** [comment]
If it works without useExistingCss that means whatever css you're providing is making that space between the pages. In my projects I supply a display type of block to print, since the flex display you're using is likely causing you problems on printing.
```
@media print {
    div {
        display: block !important;
        width: auto !important;
        float: none !important;
        position: static !important;
        overflow: visible !important;
        color: black !important;
    }
}
```

**Comment by SeKutai** [comment]
Ok Thanks for the help. I tried your suggestion but the blank space still exists. I'll keep looking though. Thanks again.

**Comment by SeKutai** [comment]
Turns out that I needed to set the height of the div inside of the print area to 100%
Thanks again for the help @Core121
