### ISSUE TITLE
Release versions for Angular 16 (and 17)

### ISSUE THREAD

**Issue by Devvox93** [selemxmn/ngx-print#172]
In PR #170 support for Angular 17 (and in [this specific commit](https://github.com/selemxmn/ngx-print/pull/170/commits/a6b2ec9e4b1777c1abd5f5af6eb997922196b645) Angular 16) has been included, but no such builds/versions have been released. The last release to NPM was about a year ago.
One of my (dependent) teams uses this package and our package is currently Angular 16+. They cannot use our package unless this package has an Angular 16 build/version as well.

Please release versions for Angular 16 and 17 to NPM, or in general a more recent version than over a year ago.

**Comment by Core121** [comment]
Ya I see your point, let me get my versions all straightened out and I'll see what I can get approved from the owners of the repo.

**Comment by Core121** [comment]
This has been completed in v1.4.0 for angular 16 and v1.5.0 for angular 17
