### ISSUE TITLE
Property '"previewOnly"' is incompatible with index signature.  Type '{ alias: "previewOnly"; required: false; }' is not assignable to 'string'

### ISSUE THREAD

**Issue by rodmjay** [selemxmn/ngx-print#178]
**Describe the bug**
When upgrading to 1.5 from 1.2 I get get compile error 

**To Reproduce**
upgrade to 1.5 version 

**Expected behavior**
No compile errors

**Screenshots**

**Ngx-Print Version**
1.5

**Desktop (please complete the following information):**
 - VS Code

**Comment by Core121** [comment]
What version of angular are you on?

**Comment by rodmjay** [comment]
15.2.9

**Comment by Core121** [comment]
Angular 15.2.9 should still be on 1.3.1. Unfortunately 1.5.x isn't supported on Angular 15.
Our readme shows which ngx-print versions support each version of angular.
![image](https://github.com/selemxmn/ngx-print/assets/42871786/2c2c0d6e-3abc-437a-8cc5-9eb3ac617243)
