### ISSUE TITLE
Optional Parameter printTitle Set Function Not Working

### ISSUE THREAD

**Issue by muncheewaffle99** [selemxmn/ngx-print#179]
**Describe the bug**
When using the printTitle optional parameter. The title is not set when saving to a pdf.

**To Reproduce**
Set the optional parameter printTitle equal to a non-null string.

**Expected behavior**
The string set in printFile should be shown in the header and should act as the file name when saving the pdf.

**Screenshots**
- Optional Parameter Usage
![image](https://github.com/selemxmn/ngx-print/assets/135360327/e6e7f3b3-8421-4aee-903c-8d20df311bdd)

- File Name when Saving
![image](https://github.com/selemxmn/ngx-print/assets/135360327/58ba1494-c02a-4c36-9465-8a41ef54bd24)

- Reverts to Default Title
![image](https://github.com/selemxmn/ngx-print/assets/135360327/62f36d8c-3dc9-4211-9112-9fb9371c8d69)

- Should be printTitle?
<img width="451" alt="image" src="https://github.com/selemxmn/ngx-print/assets/135360327/eeaeee51-22f8-4cf8-9fdf-4cb4c1133077">

**Ngx-Print Version**
v1.5.0

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by Core121** [comment]
Ya that'll do it, I'll get that fixed as soon as I can. Thanks for tracking this down.
