### ISSUE TITLE
Problem with styling а table

### ISSUE THREAD

**Issue by sapabg** [selemxmn/ngx-print#18]
**Describe the bug**
It seems that the style is not applying properly or I am doing something wrong.

**To Reproduce**
https://stackblitz.com/edit/angular-jnqdv1

**Expected behavior**
Table cells should not have consistent 1px border oll over

**Comment by selemxmn** [comment]
@sapabg Thank you (again) for using `ngx-print`, yes, seems there's something that's not working properly. I'll investigate on this, label it (bug, enhancement..) and try to fix it ASAP. Stay tuned !

**Comment by selemxmn** [comment]
@sapabg Am very sorry, I had emergencies, thus i couldnt return to your issues, I'll update them ASAP (till this weekend), sorry :disappointed:

**Comment by selemxmn** [comment]
Fixed in `ngx-print@1.2.0-beta.1` ([here](https://github.com/selemxmn/ngx-print/issues/29#issuecomment-492073262)).
