### ISSUE TITLE
NgxPrintService is missing in v1.3.1

### ISSUE THREAD

**Issue by catchmeeh1234** [selemxmn/ngx-print#180]
**Describe the bug**
NgxPrintService cannot be injected to component's constructor

**To Reproduce**
Inject NgxPrintService to component's constructor

**Expected behavior**
To be able to inject NgxPrintService to a component

**Ngx-Print Version**
ngx-print version 1.3.1

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 120.0.6099.110 (Official Build) (64-bit)

I wanted to use ngx print as a service. my use case is when a button is pressed i want to do something AND print something using ngx-print

**Comment by Core121** [comment]
The print service isn't available until 1.5.x, so that makes sense. Are you able to update to 1.5?

**Comment by Core121** [comment]
#183 specifies which versions the ngxPrintService is supported on.
