### ISSUE TITLE
  Property '"previewOnly"' is incompatible with index signature.

### ISSUE THREAD

**Issue by robinlieson92** [selemxmn/ngx-print#189]
I updated from version 1.3 to 1.5 and get this error
Can you find out what causes it?
I still use Angular 15 without updating to Angular 17

It show : 
 ```
 Property '"previewOnly"' is incompatible with index signature.
    Type '{ alias: "previewOnly"; required: false; }' is not assignable to type 'string'
```
    
And did a check on node_modules which caused it to be this : 
`static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPrintDirective, "button[ngxPrint]", never, { "previewOnly": { "alias": "previewOnly"; "required": false; }; "printSectionId": { "alias": "printSectionId"; "required": false; }; "printTitle": { "alias": "printTitle"; "required": false; }; "useExistingCss": { "alias": "useExistingCss"; "required": false; }; "printDelay": { "alias": "printDelay"; "required": false; }; "closeWindow": { "alias": "closeWindow"; "required": false; }; "bodyClass": { "alias": "bodyClass"; "required": false; }; "openNewTab": { "alias": "openNewTab"; "required": false; }; "printStyle": { "alias": "printStyle"; "required": false; }; "styleSheetFile": { "alias": "styleSheetFile"; "required": false; }; }, {}, never, never, true, never>;`

I can't update Angular, because it will cause errors everywhere, so is it possible to update canvas to image in version 1.3? I need that function on version 1.3

**Comment by eddytnk** [comment]
I am have same issue with angular v15 and "ngx-print": "^1.3.1",

**Comment by Core121** [comment]
You'd have to use the correct version of the package that supports your angular version unfortunately.
![image](https://github.com/user-attachments/assets/815be699-752e-4081-9521-c9cd9b72d0d1)

You should have access to the parameter printDelay in version 1.3 which should act similarly to previewOnly when set to a high delay.
