### ISSUE TITLE
In Angular 16 It's not working 

### ISSUE THREAD

**Issue by sarangrajan948** [selemxmn/ngx-print#193]
<button class="btn btn-green ml-2 btn-sm" printSectionId="print-section"
                                        [useExistingCss]="true" ngxPrint>
                                        {{'reports.download-pdf' | translate}}<i class="fa fa-download"></i>
</button>
                                        
                                        <div id="print-branch-section">
                                        <p>Welcome</p>
                                        </div>

**Comment by Core121** [comment]
Bug report template not followed, not enough info here to provide any resolution. Please verify your ngx-print version is within 1.4.x for angular 16 and is properly imported.
