### ISSUE TITLE
ngx-print does not support the existing styles and @media print styles

### ISSUE THREAD

**Issue by KeerthiSuresh13** [selemxmn/ngx-print#21]
Add any css style to html through style sheet. Example color: red. This will not be reflected in print page and when the same is added under @media print ,not reflecting in print page.

Give more support to existing styles sheets and where as while using print style, styles for tables tr TD are not reflected

OS windows, browser: chrome and all

**Comment by selemxmn** [comment]
@KeerthiSuresh13 , hi, Thanks for using `ngx-print`, could you please elaborate more, **and answer the questions while opening a new issue (Describe the bug, To Reproduce ...)** ?

**Comment by VeltigDev** [comment]
I am having the same problem. styles.css contains:
@media print {
     /* print only styling */
}

I believe what he's saying is that these styles are not applied. Adding them via the the propertyStyle is not the best answer.

**Comment by selemxmn** [comment]
Fixed in #30
