### ISSUE TITLE
directly send to printer

### ISSUE THREAD

**Issue by arpanmaurya** [selemxmn/ngx-print#23]
Is this possible to send print job directly to a specific printer ?
i want to print directly without showing the printer choose page. i am finding this kind of functionality with angular so is this possible with this ?

**Comment by qqaimh** [comment]
me to

**Comment by myagizguler** [comment]
You should use browser flags, you can search about silent printing on chrome or opera. I need this for my project too, i solved with this. I was need just one printer for printing service. If you have multiple printer, it doesn't work for you.

**Comment by broem** [comment]
+1 @myagizguler , since this library is basically wrapping [window.print()](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) we have no control over how the browser is configured. Build flags are definitely the best way to go.
