### ISSUE TITLE
ngx-print not supported in angular library build

### ISSUE THREAD

**Issue by Jordan-Hall** [selemxmn/ngx-print#24]
**Describe the bug**
AOT fails on angular 7 library build but not in the main application build.

> BUILD ERROR
> projects\demo\src\lib\demo.component.ts.DemoComponent.html(5,5): : Directive NgxPrintDirective, Expected 0 arguments, but got 1.
> 
> Error: projects\demo\src\lib\demo.component.ts.DemoComponent.html(5,5): : Directive NgxPrintDirective, Expected 0 arguments, but got 1.
>     at Object.<anonymous> (C:\dev\printing-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\dev\printing-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
> 
> projects\demo\src\lib\demo.component.ts.DemoComponent.html(5,5): : Directive NgxPrintDirective, Expected 0 arguments, but got 1.
> 
> Error: projects\demo\src\lib\demo.component.ts.DemoComponent.html(5,5): : Directive NgxPrintDirective, Expected 0 arguments, but got 1.
>     at Object.<anonymous> (C:\dev\printing-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\dev\printing-module\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)

**To Reproduce**
Steps to reproduce the behaviour.
1. Create a new angular 7 application. 
2. ng new library print-lib
3. Use your example code as a component library code

**Expected behaviour**
No build error and allow the code to be used inside an angular library

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.4

**Additional context**
library component example
```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-demo',
  template: `
    <div id="print-section">
      <!-- ... -->
    </div>
    <button
      [printStyle]="{ h1: { color: 'red' }, h2: { border: 'solid 1px' } }"
      printSectionId="print-section"
      ngxPrint
    >
      print
    </button>
  `,
  styles: []
})
export class DemoComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

```

**Comment by selemxmn** [comment]
Fixed in 1.2.0-beta.1 thanks to @gavmck .
