### ISSUE TITLE
Can't print in a 2nd component

### ISSUE THREAD

**Issue by woj1965** [selemxmn/ngx-print#26]
**Describe the bug**
I have some components in the application. I implement ngx-print in the toplevel module, at the customers' module; the ngx-print works fine, so when I try to use in a second component I have nothing, and when I try to use the same style used in the first component I get the following error:
`ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'printStyle' since it isn't a known property of 'button'. ("n mat-raised-button color="success" printTitle="Pedido" printSectionId="print-section" ngxPrint
    [ERROR ->][printStyle]="{span : {'font-family': 'sans-serif'}, h3 : {'border': 'solid 1px'} }" >Imprimir</button>"): ng:///HistoricoModule/DetalheHistoricoComponent.html@148:4`

The code to both components are:
`<button mat-raised-button color="success" printTitle="MyTitle" printSectionId="print-section" ngxPrint
    [printStyle]="{span : {'font-family': 'sans-serif'}, h3 : {'border': 'solid 1px'} }"  >Imprimir</button>`

When I remove printStyle option, I get no erros but I get no print.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13
 - Browser: chrome
 - Version 72.0.3626.121

**Comment by selemxmn** [comment]
Hi @woj1965 , does this issue still appearing in the last version of `ngx-print` ?

**Comment by AaronLavers** [comment]
I've noticed a similar issue, in that you have to import the library in the same module as the component calling it - i.e. if I import it in the main app.module.ts, components nested in subdirectories such as app/features/child can't access it and just shows: 'Can't bind to 'printTitle' since it isn't a known property of 'button''

**Comment by broem** [comment]
This likely isn't a bug with ngx-print it's probably more of the structure of your code, how are you loading your separate modules, are you exporting/importing the correct stuff? 

That error means Angular isn't loading the module, which means your not correctly informing it of where to find the module. Can you provide some of your project structure?

**Comment by broem** [comment]
Since ngx-print is a directive it has the same scope as any other component, directive, pipe, etc.  so you must handle it as such. 

> Directives must be declared in Angular Modules in the same manner as components.
