### ISSUE TITLE
Add styles by passing the css file names to enable multple styles

### ISSUE THREAD

**Issue by deeplotia** [selemxmn/ngx-print#29]
**Is your feature request related to a problem? Please describe.**
It would be better if we could load the css files in the print window html. So that if there are multple styles that needs to be applied than no need to pass those cumbersome css through [printStyle] attribute.

**Describe the solution you'd like**
Just pass the css names to something like [styleSheetFile] tag and append it to <link> tag of pring window screen.

**Comment by nguyenkien278** [comment]
Hi selemxmn,
i have issue as deeplotia,
for now, i want to write style for print-section as:
`'.table-list-items' : {
            'color': 'yellow',
            'border-top': '1px solid red',
            'border-right': '1px solid green',
        },`
instead of 
`'.table-list-items' : {
            'color': 'yellow',
        },`
`'.table-list-items' : {
            'border-top': '1px solid red',
        },`
`'.table-list-items' : {
            'border-right': '1px solid green',
        },`

thank you

**Comment by selemxmn** [comment]
Hi @nguyenkien278 , Thank you for using `ngx-print`, your issue is fixed and should be released very soon. There's already a created issue for that **#25**.

**Comment by nguyenkien278** [comment]
Hi selemxmn,
thank for your reply,
i've seen that option in your button element:
`<button
styleSheetFile="assets/css/custom1.css,assets/css/custom2.css"
printSectionId="print-section"
ngxPrint>print</button>`

but can you tell me where can i place this file in my project:
because i place it in src/assets/css and src/app/COMPONENT_NAME/assets/css
both them are not receive css style
[http://prntscr.com/nnuno1](url)
[http://prntscr.com/nnuo8z](url)
here is my screenshort, where i place css file for print-section

thank you so much!

**Comment by selemxmn** [comment]
@nguyenkien278 ,

That was a mistake, In fact it was a merged pull request to the master which contains the described functionality and not released yet. Am baking it right now, Today you'll get it.

You're so welcome !

**Comment by nguyenkien278** [comment]
Thank you so much @selemxmn !

**Comment by deeplotia** [comment]
Also @nguyenkien278 for `styleSheetFile="assets/css/custom1.css,assets/css/custom2.css"` feature to make it work. The CSS files needs to be present in src/assets/css/CSS_NAME.

**Comment by nguyenkien278** [comment]
Hi @deeplotia and @selemxmn ,
thank you so much for your guide and reply,
I tried to use `styleSheetFile="assets/css/custom1.css,assets/css/custom2.css"` and place css file in: **_src\assets\css\custom1.css_** but print window still doesn't get style, 
will it work on next release?

**Comment by selemxmn** [comment]
@nguyenkien278 , latest one now is 1.2.0-beta.1.
