### ISSUE TITLE
print is preprended with words Undefined Undefined

### ISSUE THREAD

**Issue by scottlove** [selemxmn/ngx-print#34]
Output of print shows as:  undefined undefined Hello World

Code snippet:  
  <div id="print-section1">
    Hello World
  </div>
  <button printSectionId="print-section1" ngxPrint>
    Print
  </button>

Running Angular 7 app in google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
on Windows 7

I got this same behaviour in my app so I simplified it down to the basic snippet.  Full code of the component I am trying to use this in is:
<mat-card>
  <mat-card-title>Ingredients</mat-card-title>
  <div>
    <mat-list>
      <mat-list-item *ngIf="recipe.NOAH > 0"
        >NOAH: {{ recipe.NOAH }} {{ recipe.settings.Units }}</mat-list-item
      >
      <mat-list-item *ngIf="recipe.KOH > 0"
        >KOH: {{ recipe.KOH }} {{ recipe.settings.Units }}</mat-list-item
      >
      <mat-list-item>Water: {{ recipe.water }} {{ recipe.settings.Units }}</mat-list-item>
      <mat-list-item
        >Fragrance: {{ recipe.fragrance }} {{ recipe.settings.Units }}</mat-list-item
      >
      <mat-list-item *ngFor="let oil of recipe.oils"
        >{{ oil.Name }}: {{ oil.Weight }} {{ recipe.settings.Units }}</mat-list-item
      >
    </mat-list>
  </div>
  <mat-card-footer *ngIf="recipe.NOAH > 0"> *97% purity NOAH</mat-card-footer>
  <mat-card-footer *ngIf="recipe.KOH > 0">*90% purity KOAH</mat-card-footer>
  <div id="print-section1">
    Hello World
  </div>
  <button printSectionId="print-section1" ngxPrint>
    Print
  </button>
</mat-card>

**Comment by scottlove** [comment]
code snippet got reformated: code was simple div with hello world with button for print using sample from reposoitory

**Comment by a-alkamel** [comment]
the same here

**Comment by selemxmn** [comment]
Thank you for using `ngx-print`, Fixed in **#35** , released new version `ngx-print@1.2.0-beta.2`.

**Comment by scottlove** [comment]
Tested fix and it works great.  Already released out to prod today with our app.
