### ISSUE TITLE
The package doesn't work in angular 4

### ISSUE THREAD

**Issue by Engshreen** [selemxmn/ngx-print#36]
@selemxmn 

After installing the package in angular 4 i can't use it always gives me the following error
Metadata version mismatch for module node_modules/ngx-print/ngx-print.d.ts, found version 4, expected 3.

I use 
 - Windows 10
 - Browser chrome
 - Angular version 
@angular/cli: 1.4.10
node: 10.15.3
os: win32 x64
@angular/animations: 4.4.7
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.10
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by laurentyhuel** [comment]
@Engshreen Did you found a solution ?

**Comment by Sam-Davis** [comment]
I had this issue on 1.2.0-beta3. It worked until I restarted the angular project. I did not find a solution.

**Comment by broem** [comment]
Closing for stale, please open another issue if this continues.
