### ISSUE TITLE
[useExistingCss] doesn't seem to work on Safari

### ISSUE THREAD

**Issue by wesley-wong** [selemxmn/ngx-print#37]
**Describe the bug**
On safari, I was getting a blank page when printing. It started working again after I removed the [useExistingCss]="true", but then it wasn't styled. I have global styles and component level styles, and this seemed to work on 

**To Reproduce**
add [useExistingCss]="true"
use safari

I tried to do the above on this project https://stackblitz.com/edit/demo-ngx-print?file=src%2Fapp%2Fapp.component.html
1) update ngx-print
2) add [useExistingCss]="true"
3) Attempt to print
Safari behaves weirdly.

**Expected behavior**
New tab and can print as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Browser: Safari 12.0.3
 - Version: ngx 1.2.0-beta.2

I think the issue most likely has something to do with the `<body onload=window.print();window.close()>`, it seems to attempt to print before all the css is loaded

**Comment by Thorski** [comment]
I put useExistingCss on the above mentioned StackBlitz: 

`<button [useExistingCss]="true" printSectionId="demo" ngxPrint>print</button>`

I get the error:
```
Template parse errors:
Can't bind to 'useExistingCss' since it isn't a known property of 'button'. ("
```

Which is the same error I get when I try to use it with ngx-print installed and imported into my NgModule.   However, if I copy the directive code locally, it works fine.  

-- Thor

**Comment by selemxmn** [comment]
@Thorski , hi and thanks for using `ngx-print`.
Please, feel free to open a new issue if yours is not related to the already opened one.
However, for your issue, it is because of the installed `ngx-print` version in the stackblitz project which is `1.1.0`  and it does not include the `[useExistingCss]` feature **(that property was added in the _1.2.0-beta.1_)**
Salem :)

**Comment by Thorski** [comment]
Thank you.   I used 1.2.0-beta.2 and now everything is lovely.

**Comment by TarunPurohit1437** [comment]
![image](https://user-images.githubusercontent.com/26676333/59902587-48082800-941c-11e9-9533-ea12208f3c55.png)
![image](https://user-images.githubusercontent.com/26676333/59902610-59513480-941c-11e9-9ee5-5b6a00b03e1d.png)


It is working fine on Chrome but not working on Safari After removing [useExistingCss]="true"  print preview is working in safari but I want it to work with using existing css same as it working in Chrome firefox.

I have also user npm install ngx-print@1.2.0-beta.2   latest but not working in safari

**Comment by iSens** [comment]
> ![image](https://user-images.githubusercontent.com/26676333/59902587-48082800-941c-11e9-9533-ea12208f3c55.png)
> ![image](https://user-images.githubusercontent.com/26676333/59902610-59513480-941c-11e9-9ee5-5b6a00b03e1d.png)
> 
> It is working fine on Chrome but not working on Safari After removing [useExistingCss]="true" print preview is working in safari but I want it to work with using existing css same as it working in Chrome firefox.
> 
> I have also user npm install ngx-print@1.2.0-beta.2 latest but not working in safari

I have the same issue, doesn't work on Safari with [useExistingCss]="true" .

Any help?

**Comment by iSens** [comment]
every time i click the print button, a new window open on top of Safari and disappear in a second...
![2019-09-10_0824](https://user-images.githubusercontent.com/205632/64613988-7820f080-d3a5-11e9-9a82-a263009f12c0.png)

**Comment by iSens** [comment]
Thanks for fixing a Safari issue... updated the package and everything working properly....

will verify on iPad and iPhone....

**Comment by selemxmn** [comment]
@wesley-wong, did the latest update fix your issue ?

**Comment by iSens** [comment]
yes, thanks!

I will test on iPad and iPhone next week...

**Comment by PriyoGitHub** [comment]
I am using bellow two versions but it is not working in iPad(Safari browser), like, clicking on the print button of the website the print dialog box is disappearing after 2-3 seconds and  also crashing the safari browser as well. 

"ngx-print": "^1.2.0-beta.2",
"ngx-print": "^1.2.0-beta.3",

I have tried adding/removing [useExistingCss]="true" code, is also not working.

**Comment by MyoHtutAung** [comment]
[useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process.

**Comment by pavankjadda** [comment]
> [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process.

@MyoHtutAung Were you able to solve this issue? I am facing same issue

**Comment by harbons** [comment]
> > [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process.
> 
> @MyoHtutAung Were you able to solve this issue? I am facing same issue

I also had that error on local process compiling, but print button worked right on Chrome/Firefox.
Not yet tested on deploy, but locally using useExistingCss="true" (without square brackets) solved compiling error.
Using latest ngx-print 1.2.0-beta.5 .

Maybe update readme can help?

**Comment by broem** [comment]
This issue should be resolved with most recent release 1.2.0-beta.6

**Comment by udurai-pinc** [comment]
Can't bind to 'useExistingCss' since it isn't a known property of 'button'.       

11             <button ngxPrint [useExistingCss]="true" printSectionId="survTable">Print</button>
                                ~~~~~~~~~~~~~~~~~~~~~~~
am using  "ngx-print": "1.3.1",  "@angular/compiler": "^15.2.2",  plz giev solution

**Comment by bschmitz9** [comment]
I am seeing the same error after a npm cache clean and update of my node-modules. Build breaks saying "Can't bind to 'useExistingCss' since it isn't a known property of 'button'" Moved to 1.2.0-beta.6 for now and it works.
