### ISSUE TITLE
Doesn't print html as it is

### ISSUE THREAD

**Issue by akshay27395** [selemxmn/ngx-print#38]
I want to print the following HTML (pic 1) but getting the output as pic 2

**Screenshots**

HTML:
![Screenshot from 2019-06-04 14-53-58](https://user-images.githubusercontent.com/35006691/58867838-c9e81980-86d8-11e9-9e58-1557826bd930.png)

Output:

![Screenshot from 2019-06-04 14-54-19](https://user-images.githubusercontent.com/35006691/58867881-d8cecc00-86d8-11e9-8e8b-4f4df951e882.png)

**Version**
5.6.0

**Comment by selemxmn** [comment]
Hi @akshay27395 , Thanks for using `ngx-print`.
Could you please amend the issue and add your HTML code snippet ?

**Comment by akshay27395** [comment]
Hi @selemxmn , this is my HTML code snippet:

<div align= "center" id="print-section">
    <p align= "center">Disbursement Memo</p>

    <div align= "center" class="col-md-6">
        <table style="width:100%">
            <tr>
              <td>Jill:</td>
              <td>Smith</td>
            </tr>
            <tr>
              <td>Eve:</td>
              <td>Jackson</td>
            </tr>
            <tr>
              <td>John:</td>
              <td>Doe</td>
            </tr>
          </table>
    </div>

    <div align= "center" class="col-md-6">
      <table style="width:100%">
          <tr>
            <td>Jill:</td>
            <td>Smith</td>
          </tr>
          <tr>
            <td>Eve:</td>
            <td>Jackson</td>
          </tr>
          <tr>
            <td>John:</td>
            <td>Doe</td>
          </tr>
        </table>
  </div>

<div>
        <button [printStyle]="{h1 : {'color': 'red'}, h2 : {'border': 'solid 1px'}}" printSectionId="print-section" ngxPrint>print</button>
 </div>

My issue is described in the screenshots. Can you tell me what exactly you want me to explain ? I don't get any error in my console. Just that I am not getting the desired output

**Comment by NeethuVinodan** [comment]
use existingCss directive.

**Comment by vonaerich** [comment]
@akshay27395 Did you build using the --prod flag? I'm also getting the same issue but only when running in --prod. It works fine for me in development.
