### ISSUE TITLE
unable to add colors even after using [useExistingCss] directive

### ISSUE THREAD

**Issue by sushanthdornala** [selemxmn/ngx-print#40]
I am using [useExistingCss]="true" but on print i cant see my existing styles to the div

**Comment by sushanthdornala** [comment]
![bug-ngx-print](https://user-images.githubusercontent.com/51824022/59511963-4c40bc80-8ed5-11e9-9ba0-79a9dd106a0d.PNG)

As you can see in background my table header is in blur color, how to reproduce it in print-window

**Comment by sigmama** [comment]
![image](https://user-images.githubusercontent.com/52157539/60872347-1d64fe80-a267-11e9-80b4-a5e43b75ae72.png)
 @sushanthdornala try getting the circled setting checked.

**Comment by AhsanAyaz** [comment]
@sushanthdornala See my answer on another issue of this repo..  https://github.com/selemxmn/ngx-print/issues/39#issuecomment-529640330

**Comment by broem** [comment]
I would also look at wrapping your styles in media print queries as well.
