### ISSUE TITLE
Print Preview always open in new tab

### ISSUE THREAD

**Issue by usmansaleh** [selemxmn/ngx-print#41]
**Option to print preview in the same tab.**
Print preview always opens in a new tab, I need an option for the printing preview in the same tab.

**Comment by awaism551** [comment]
Any progress in this??

**Comment by Emperor577** [comment]
what about this issue? any body find the solution ?

**Comment by Vatsalya-singhi** [comment]
Hi, thank you for this module. This still seems to be an open issue. Any progress as to when it will get resolve?

**Comment by broem** [comment]
I'll go ahead and take a look this week

**Comment by yooziPi** [comment]
> I'll go ahead and take a look this week

Would you let me know how's it going?

**Comment by broem** [comment]
A change like this would require a large refactor of the library, I'm thinking of ideas but haven't landed on anything usable at this time.

**Comment by yooziPi** [comment]
> A change like this would require a large refactor of the library, I'm thinking of ideas but haven't landed on anything usable at this time.

yap! thank you for the reply :)

**Comment by narendrakolluru** [comment]
> A change like this would require a large refactor of the library, I'm thinking of ideas but haven't landed on anything usable at this time.

Any Updates on this issue.?Let me know if any..
