### ISSUE TITLE
useExistingCss only works in develop mode

### ISSUE THREAD

**Issue by sigmama** [selemxmn/ngx-print#43]
**Describe the bug**
After production build the application with Angular CLI, the 'useExistingCSS' directive does not take effect. the SPA is developed with angular 7.

**Expected behavior**
Production build apps performs the same as is in developing mode.

**Screenshots**
-- developing mode:
![image](https://user-images.githubusercontent.com/52157539/60794526-89c6fb80-a19c-11e9-85d7-77c74075403d.png)
-- production build:
![image](https://user-images.githubusercontent.com/52157539/60794424-54221280-a19c-11e9-886f-1c7db47c64cb.png)

**Comment by sigmama** [comment]
I have do some work around on this issue and found that it is related to the 'useHash' flag in Angular.
In production build, I set it as 'false' while in develop mode it is 'true'. But I still want to know whether it can be fixed even if we set the flag as 'false'.

**Comment by jpsmedeiros** [comment]
I'm having a similar problem, it works fine with the local server, but when I use `ng build --prod` and deploy the application the print does not use the bootstrap grid styles, but it uses the styles that I created.

@sigmama the styles that you are using are from bootstrap too? Maybe It's a problem when using the bootstrap classes.

**Comment by sigmama** [comment]
Yeah but I don't believe bootstrap classes will be a cause while I think it should be a path related issue.
I'll pull the library locally and will play with it a little bit to see whether I can get a solution locally.

**Comment by sigmama** [comment]
Hi @jpsmedeiros, 
I have verified this is a path related issue.
In develop mode, all the vendor styles will be kept in <style> elements while in production build they are combined in a css file such as '\<link rel="stylesheet" href="styles.css" />' in the index.html.
'ngx-print' will just copy either \<style> elements or \<link> elements into print output page and result in file path issue.
For example, if you print something on a page whose link is 'http://[approot]/samplepage', the file path in the output window will be
'http://[approot]/samplepage/styles.css' instead of the expected link of 'http://[approot]/styles.css'.
So I just edited the link tag as \<link rel="stylesheet" href="/[approot]/styles.css" /> to solve my issue.

**Comment by jfillipe** [comment]
I have same problem here. Anyone can help-me?

**Comment by jpsmedeiros** [comment]
@jfillipe useHash **true** did the trick for me

**Comment by ShivPandey** [comment]
> Hi @jpsmedeiros,
> I have verified this is a path related issue.
> In develop mode, all the vendor styles will be kept in <style> elements while in production build they are combined in a css file such as '<link rel="stylesheet" href="styles.css" />' in the index.html.
> 'ngx-print' will just copy either <style> elements or <link> elements into print output page and result in file path issue.
> For example, if you print something on a page whose link is 'http://[approot]/samplepage', the file path in the output window will be
> 'http://[approot]/samplepage/styles.css' instead of the expected link of 'http://[approot]/styles.css'.
> So I just edited the link tag as <link rel="stylesheet" href="/[approot]/styles.css" /> to solve my issue.

yeh ! itss working well !

**Comment by StefanoWork4Me** [comment]
I used a workaround like this one to make it to work on both dev and production environments.

```
this.useExistingCss = true;
if (environment.production) {
      this.useExistingCss = false;
      const elements = document.getElementsByTagName('link');
      for (let index = 0; index < elements.length; index++) {
        if (elements[index].href.startsWith(document.baseURI)) {
          this.styleName += elements[index].href + ',';
        }
      }
      this.styleName = this.styleName.slice(0, -1);
    }
```

This in the HTML
```
<button class="no-print" type="button" pButton icon="fas fa-print" label="Print"
                        printTitle="Title"
                        printSectionId="print-section"
                        styleSheetFile="{{styleName}}"
                        [useExistingCss]="useExistingCss" ngxPrint></button>

```
Hope it helps.

**Comment by elamranisouhail** [comment]
> I used a workaround like this one to make it to work on both dev and production environments.
> 
> ```
> this.useExistingCss = true;
> if (environment.production) {
>       this.useExistingCss = false;
>       const elements = document.getElementsByTagName('link');
>       for (let index = 0; index < elements.length; index++) {
>         if (elements[index].href.startsWith(document.baseURI)) {
>           this.styleName += elements[index].href + ',';
>         }
>       }
>       this.styleName = this.styleName.slice(0, -1);
>     }
> ```
> 
> This in the HTML
> 
> ```
> <button class="no-print" type="button" pButton icon="fas fa-print" label="Print"
>                         printTitle="Title"
>                         printSectionId="print-section"
>                         styleSheetFile="{{styleName}}"
>                         [useExistingCss]="useExistingCss" ngxPrint></button>
> ```
> 
> Hope it helps.

in whitch place should we do this block ??

**Comment by StefanoWork4Me** [comment]
The javascript goes in component that you want to print, in the ngOnInit function, where also the html goes.

**Comment by StefanoWork4Me** [comment]
> > I used a workaround like this one to make it to work on both dev and production environments.
> > ```
> > this.useExistingCss = true;
> > if (environment.production) {
> >       this.useExistingCss = false;
> >       const elements = document.getElementsByTagName('link');
> >       for (let index = 0; index < elements.length; index++) {
> >         if (elements[index].href.startsWith(document.baseURI)) {
> >           this.styleName += elements[index].href + ',';
> >         }
> >       }
> >       this.styleName = this.styleName.slice(0, -1);
> >     }
> > ```
> > 
> > 
> > This in the HTML
> > ```
> > <button class="no-print" type="button" pButton icon="fas fa-print" label="Print"
> >                         printTitle="Title"
> >                         printSectionId="print-section"
> >                         styleSheetFile="{{styleName}}"
> >                         [useExistingCss]="useExistingCss" ngxPrint></button>
> > ```
> > 
> > 
> > Hope it helps.
> 
> in whitch place should we do this block ??

The javascript goes in the component that you want to print, in the ngOnInit function, where also the html goes. You can add it as it is (not really advised) to a component or (better) create a class to import when needed.

**Comment by MyoHtutAung** [comment]
I also get that error. [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process. What should i do?

**Comment by ShivPandey** [comment]
> I also get that error. [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process. What should i do?

after build production add the "/" to styleSheet path 
default : <link rel="stylesheet" href="styles.e8e0c4d482c7002d5ea1.css"></head>
updated: <link rel="stylesheet" href="/styles.e8e0c4d482c7002d5ea1.css"></head>

**Comment by elamranisouhail** [comment]
> I also get that error. [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process. What should i do?

  *** Hello ***

To resolve this Issue , you should put a specific (file css) for your Template , 
it's work for me like that :

`<button 
type="button" 
styleSheetFile="../../assets/css/contrat.css" 
type='button' 
[printSectionId]="inlineOption" 
ngxPrint  
class="btr btn btn-outline-secondary btn-sm">
PRINT</button>`

**Comment by dkruchok** [comment]
> I also get that error. [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process. What should i do?

Try next thing
In your dist folder in your production build find to edit the index.html file and change your style href link (example)
`<link rel="stylesheet" href="styles.a37209b9d07af7d9b12a.css"></head>`
to
`<link rel="stylesheet" href="/styles.a37209b9d07af7d9b12a.css"></head>`

Also, opening the print button in a new window also makes me a trick.

**Comment by xdrago1** [comment]
This is still a problem. The solution of @dkruchok  worked. But I do not want to add the "/" manually every time I build the project. Any better solution?

**Comment by Basher7** [comment]
Any better solution without adding '/' after every production build?

**Comment by jairmedeiros** [comment]
Problem still present in the 1.2.0-beta.5

**Comment by elvispdosreis** [comment]
I also have the same problem using the angular: 10.0.3 and ngx-print: 1.2.0-beta.5

**Comment by EnochGao** [comment]
> This is still a problem. The solution of @dkruchok worked. But I do not want to add the "/" manually every time I build the project. Any better solution?

Hello, have you solved it

**Comment by EnochGao** [comment]
> is there have any better solution without adding '/' after every production build?

Hello, have you solved it

**Comment by EnochGao** [comment]
> > I also get that error. [useExistingCss] = "true" doesn't work when i deploy the code. It works only on local process. What should i do?
> 
> Try next thing
> In your dist folder in your production build find to edit the index.html file and change your style href link (example)
> `<link rel="stylesheet" href="styles.a37209b9d07af7d9b12a.css"></head>`
> to
> `<link rel="stylesheet" href="/styles.a37209b9d07af7d9b12a.css"></head>`
> 
> Also, opening the print button in a new window also makes me a trick.
> 
> Also, check this issue here, if you do not see the text, this guy added delay
> #62

I soled it. We can add "deployUrl": "/" to the Architect configuration options in the Angular.json file,
```json
    "architect": {
      "build": {
        "builder": "@angular-devkit/build-angular:browser",
        "options": {
          "outputPath": "dist",
          "index": "src/index.html",
          "main": "src/main.ts",
          "polyfills": "src/polyfills.ts",
          "tsConfig": "tsconfig.app.json",
          "aot": true,
          `deployUrl: /`
      },
```
