### ISSUE TITLE
Image is not getting printed with ngx-print. 

### ISSUE THREAD

**Issue by MrHuBz** [selemxmn/ngx-print#45]
Image is not getting printed with ngx-print. 
However the image is visible on the screen , but not visible in the print preview section.

```
<button  type="button" printTitle="PrintVoucher" [useExistingCss]="true" 
                                        printSectionId="printVoucher" ngxPrint>
                                        Print </button>
```
```
<div row id="printVoucher" >
 <img  src="assets/images/logo.png">
</div>
```

**Comment by rlagkrdy** [comment]
Hi.
Print window not open in your project. It's open new window.
So, Should be use absolute path , Not relative path

**Comment by agamgupta6** [comment]
Yes..I am facing the same issue for image printing with ngx-print..And it is not a problem of the path.

**Comment by broem** [comment]
Do you have a way of reproducing this? I am unable to, I can load and print from local assets as well as hosted images.

**Comment by broem** [comment]
This seems to be working
