### ISSUE TITLE
Blank Print preview in iPad

### ISSUE THREAD

**Issue by lkpatir** [selemxmn/ngx-print#46]
The print action produces blank print preview in iPad. If printed, it just prints blank screen. I tried it even with a simple text eg "Hello World" inside print section but it produces the same issue. Other than iPad, it works in all other devices, please help.

Sample code:
    <button printSectionId="print-section" ngxPrint>Print</button>
    <div id="print-section">Hello World</div>

**Comment by selemxmn** [comment]
@lkpatir , Did the latest update fix your issue ?

**Comment by lkpatir** [comment]
Hi @selemxmn 
As you can see, I didnot have any fixing code. Since I didnot get any reply, I removed this plugin and simply used javascript print method using window.open method. But i can tell what the issue is with Ipad browser (i used Safari): The ngx print use target="_blank" for the printing action and in Ipad, whichever link opens with this way, the window is considered opened as "popup". If the "Block Popup" option is enabled in the browser, then the blank issue happens. If the option is disabled, then it the preview is not blank and it prints properly. This was not desired for me, so I removed it and used window.open method to detect if the popup option is disabled to alert user and javascript print method to print.

**Comment by PriyoGitHub** [comment]
I am using bellow two versions but it is not working in iPad(Safari browser), like, clicking on the print button of the website the print dialog box is disappearing after 2-3 seconds and  also crashing the safari browser as well. 

"ngx-print": "^1.2.0-beta.2",
"ngx-print": "^1.2.0-beta.3",

I have tried adding/removing [useExistingCss]="true" code, is also not working.

**Comment by lkpatir** [comment]
Hi @PriyoGitHub 

Dont use Ngx print, it doesnot work on iPad. Simply use pure Javascript window.print using window.open. Also use pure javascript to detect if user has enabled popup blocking to alert
