### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by PortStone** [selemxmn/ngx-print#48]
Print dialog will open in an additionally window which has the title of name from package.json which means you can't have an uppercase first letter. Is it possible to just set a custom name?

**Comment by selemxmn** [comment]
@PortStone , Sorry did not get the issue, could you answer the asked questions while submitting the issue, please ?

**Comment by PortStone** [comment]
I don't really understand you answer. Anyways it's only behaving like this in my old project which uses nw.js and Angular to create a native app. I am currently using Angular without nw.js because I replaced it with PWA. Now it is creating a new window which is titled "Untitled - Google Chrome" (using Google Chrome as my browser). Which I can easy change with printTitle. For example `printTitle="Invoice Creator - Print" `will create a new window with the title "Invoice Creator - Print - Google Chrome" which means I can change the tab name. I don't know if - Google Chrome is supposed behavior. So you can close this issue because it is related to nw.js which I don't use anymore.
