### ISSUE TITLE
How to add styles with Print window in this module

### ISSUE THREAD

**Issue by Sanjeev-Saraswat-igt** [selemxmn/ngx-print#5]
I have used this ngx-print.but after click on print ,i am not getting mypage css styles.

**Comment by selemxmn** [comment]
@Sanjeev-Saraswat-igt , thank you for your feedback, actually, the lib does not support this feature for now, but it was intended to be released very soon. Stay tuned maybe the upcoming 3 days you'll be able to  add your own styles :smiley:

**Comment by nayakantimounika** [comment]
@selemxmn  
Hi,
When can we expect the newly added feature(Own Styles) for ngx-print

**Comment by selemxmn** [comment]
@Sanjeev-Saraswat-igt today before midnight (UTC) :smile:

**Comment by selemxmn** [comment]
https://github.com/selemxmn/ngx-print/commit/71cefdf

**Comment by selemxmn** [comment]
This issue has been solved here https://github.com/selemxmn/ngx-print/commit/71cefdf

**Comment by Sanjeev-Saraswat-igt** [comment]
Thanks... We will update our dependencies and hope we will get good feature

Android ?? ??? Outlook<https://aka.ms/ghei36> ??????? ????

________________________________

**Comment by selemxmn** [comment]
@Sanjeev-Saraswat-igt Feel free to report any suspicous behaviour :)

**Comment by twaghmiles** [comment]
`[printStyle]` is not accepting multiple style. So when we do `[printStyle]="{div : {'color': 'red', 'margin': '10px'}, h2 : {'border': 'solid 1px'}}"` It is not adding any style to div.

**Comment by selemxmn** [comment]
@twaghmiles Please open a new issue and I'll refer your comment there; since the reporter of the current one did not plain about the fix. Thanks for your feedback :smile:
