### ISSUE TITLE
Input values are not getting printed.

### ISSUE THREAD

**Issue by ArshathS** [selemxmn/ngx-print#52]
**Form controls values are not getting displayed in print screen**
For example, if I have an element like below.
`              <input name="shipTo" #shipTo="ngModel" [(ngModel)]="invoiceService.formDate.shipTo" type="text" class="form-control" placeholder="Ship To" [disabled]="invoiceService.formDate.paymentStatus=='Paid'">`

It is not getting displayed. 

Can anyone look into this and let me know as soon as possible.
Web page as shown in the screen shot.
![image](https://user-images.githubusercontent.com/35331259/65371712-0f2e5800-dc84-11e9-82f2-56b3718e89c6.png)

Print Screen as shown below.
![image](https://user-images.githubusercontent.com/35331259/65371818-30437880-dc85-11e9-877c-fb164167a2ce.png)

**Comment by varunkhambra** [comment]
I have same issue, but its strange, it prints for the table but not for the input fields above the table. But i believe we can solve it. I am trying when resolved, will post.

**Comment by perluqing** [comment]
mark,I have this too
angular8,chrome 77

**Comment by arun-ab** [comment]
any updates on this?

**Comment by belvincharles** [comment]
4326537

**Comment by belvincharles** [comment]
I have same issue

**Comment by emreh** [comment]
I have same issue, tooooooo
