### ISSUE TITLE
Use ngxPrint with anchor tag?

### ISSUE THREAD

**Issue by IRCraziestTaxi** [selemxmn/ngx-print#54]
**Is your feature request related to a problem? Please describe.**
I attempted to use `ngxPrint` with an `<a>` tag but nothing happened when I clicked it. Using a `<button>` instead allowed it to work.

**Describe the solution you'd like**
I would like to use an `<a>` tag rather than a `<button>` for stylistic reasons.

**Comment by naingyelin** [comment]
try something like this , idea is to trigger the click event of the hidden button from another element, also look at material buttons, the have buttons that can look like anchor tag
`<button type="button" style="visibility: hidden" #print ngxPrint 
                printSectionId="print-section"></button>
<a onclick="print.click()">print</a>`

**Comment by broem** [comment]
closing this, because that should work
