### ISSUE TITLE
Print Issue

### ISSUE THREAD

**Issue by NageshVitta** [selemxmn/ngx-print#58]
**Describe the bug**
Text is breaking into next page. Attached the screenshot.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
When text is exceeding the page it should not cut the words. It should move the data into next page.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 78.0.3904.87 (Official Build) (64-bit)

**Additional context**
![img](https://user-images.githubusercontent.com/57523163/68463229-2fb27180-0234-11ea-963e-bb176da359db.PNG)

**Comment by Metalick** [comment]
Any workarounds on this? Experiencing the same problem here.

**Comment by broem** [comment]
rolling into #78
