### ISSUE TITLE
content not showing on print preview

### ISSUE THREAD

**Issue by hussainwali74** [selemxmn/ngx-print#61]
if the number of pages is more than 5 the content is not loaded properly, I have tried all the workarounds I found in the issues (closed/opened) on the repo please help:
@selemxmn @broem @AhsanAyaz 
![image](https://user-images.githubusercontent.com/24194686/69899104-756de000-1383-11ea-907c-81c90cb8e9cd.png)

**Comment by narayanandayalan** [comment]
Yes, even i'm facing the same issue, even though i have 2 pages of content. 

Any solution?

**Comment by hussainwali74** [comment]
@selemxmn  ??

**Comment by broem** [comment]
could you provide your **package.json** and browser info? @hussainwali74

**Comment by hussainwali74** [comment]
@broem 
 "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "@auth0/angular-jwt": "^3.0.1",
    "@fullcalendar/core": "4.0.2",
    "@fullcalendar/daygrid": "4.0.1",
    "@fullcalendar/interaction": "4.0.2",
    "@fullcalendar/timegrid": "4.0.1",
    "@types/jspdf": "^1.3.3",
    "chart.js": "2.7.3",
    "dom-to-image": "^2.6.0",
    "html2canvas": "^1.0.0-rc.5",
    "intl": "1.2.5",
    "jspdf": "^1.5.3",
    "ngx-print": "^1.2.0-beta.3",
    "primeflex": "1.0.0-rc.1",
    "primeicons": "1.0.0",
    "primeng": "8.0.0",
    "prismjs": "1.15.0",
    "quill": "^1.3.7",
    "rxjs": "6.4.0",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.2",
    "@angular/cli": "8.0.0",
    "@angular/compiler-cli": "8.0.0",
    "@angular/language-service": "8.0.0",
    "@types/jasmine": "3.3.13",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.9.5",
    "codelyzer": "5.1.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.5",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "5.4.2",
    "ts-node": "7.0.1",
    "tslint": "^5.20.1",
    "typescript": "^3.4.5"
  }

**Comment by hussainwali74** [comment]
@selemxmn ??

**Comment by narayanandayalan** [comment]
The below is the screen shot. I too face the same issue

![image](https://user-images.githubusercontent.com/26084714/70057782-c0962600-1603-11ea-9d9a-4d9667116417.png)

**Comment by broem** [comment]
I am unable to reproduce this issue, what kind of content is being loaded there? I am able to print 1000s of pages at a time. Are you able to any pages at all from that screen?

**Comment by hussainwali74** [comment]
@broem  hi, thanks for the reply. I can print few pages say less than 4 pages but if the number of pages gets more than 5 in a single print the data doesn't load on the first try and just outline boundaries of the content gets printed (screenshot in the first comment). we have to cancel the print window and try again, after few tries it loads the data.

**Comment by broem** [comment]
@hussainwali74 ok, great. I believe @davemecha has a PR in now that roughly patches this issue, I will look into cleaner solutions and submit something as well.

**Comment by hussainwali74** [comment]
@broem  @davemecha the work around works in development but when I try to get a prod build it throughs error.. any help ?
![image](https://user-images.githubusercontent.com/24194686/71466045-267b6500-27e0-11ea-9588-5b420c2a1c68.png)

**Comment by broem** [comment]
@hussainwali74 did the last release fix your issue?

**Comment by hussainwali74** [comment]
@broem yeah fixed it, thanks alot

**Comment by RamiYahyaRY** [comment]
It's back for me. Same issue, either not all pages load, or they load but with tables/style outlined and no content or values whatsoever. 
![image](https://user-images.githubusercontent.com/46673991/87509385-16db4500-c67a-11ea-9992-7bb3b27c57cd.png)

See the scrollbar on the left? It is because not all 3 pages loaded.

**Comment by MMahdi1911** [comment]
@narayanandayalan  I face the same issue but only on the prod, can you tell me how you solved it?

**Comment by arunmasta** [comment]
@narayanandayalan I am also facing the same issue, we are getting a blank screen in the prod env. could you please confirm if we had a fix for this issue
@broem
