### ISSUE TITLE
Ngx Print not working with input values - ngModel Values

### ISSUE THREAD

**Issue by miteshkumar280** [selemxmn/ngx-print#68]
I have a html form and many input values which are using ngModel for to and fro communication. But when im using ngx-print in this form, all the input values are getting empty and showing a preview to download as pdf. Also tried the same in stackblitz. Please check the image
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/46070570/73052033-25eef080-3eaa-11ea-8d34-80627a7a85f9.PNG">

**Comment by ratsey** [comment]
There are a number of issues logged for this same problem. Take a look at #55 as an example. We're waiting on an updated build.

**Comment by miteshkumar280** [comment]
@ratsey do you know any other npm packages that can be used and get the problem solved.

**Comment by juliocesarperez17** [comment]
I am having the same issue, the fields of the automated populated form are empty.
