### ISSUE TITLE
not able to attach external stylesheet using styleSheetFile property

### ISSUE THREAD

**Issue by Zankhna95** [selemxmn/ngx-print#83]
**Describe the bug**

I am using .scss file to apply styles in pdf. Styles are not getting attached.

**To Reproduce**
I have a folder structure as mention below.
Folder name -> statatistics
Inside the folder, I have 3 files
1. statistics.component.ts
2.statistics.component.html
3.statistics.component.scss

**Expected behavior**
Could you please let me know how to apply external scss file?

**Screenshots**
Expected PDF:
![image](https://user-images.githubusercontent.com/44663453/82258647-d57b3180-9977-11ea-93d3-68d639cfbd9c.png)

The result I am getting right now is :
![image](https://user-images.githubusercontent.com/44663453/82258728-ffccef00-9977-11ea-94ff-0d5505007711.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:chrome

**Comment by eriklive** [comment]
Same thing here.

**Comment by guilhermefelipesilva** [comment]
Same thing here too, but with `.css`

**Comment by derickfelix** [comment]
@Zankhna95 for now it is not possible to attach a `.scss` file, you'd need to compile first to `css` and then add it to your `/assets/`.

Lets say we have this `statistics` component. I'd create a folder `src/assets/reports`, and a `statistics.css` file inside it. Then referring to it as `<button styleSheetFile="assets/reports/statistics.css"...>...</button>`
