### ISSUE TITLE
ngx-print is not printing reactive form values in angular

### ISSUE THREAD

**Issue by nisha2107** [selemxmn/ngx-print#86]
**Describe the bug**
ngx-print is not printing reactive form values except < input> tag

**To Reproduce**
have Angular reactive form with following tags 
1. textarea (works when user enters value, but not when displaying form values 
2. radio button
4. checkbox

**Expected behavior**
values should be printed for user entries to above tags

**Screenshots**
First screen with answers:
![image](https://user-images.githubusercontent.com/17924176/84479761-0bd17580-acc6-11ea-808b-91876103e874.png)

Second screen is print preview: 
![image](https://user-images.githubusercontent.com/17924176/84479846-2e638e80-acc6-11ea-8a97-f82f7d2f11aa.png)

**Desktop (please complete the following information):**
 - OS: Windows and iOS
 - Browser [chrome, safari]

** Additional Comment**
what is more you can see on screenshot the radio option css is also missing. Color in radio options.

**Comment by weiyilang123** [comment]
I have the same issue, but i modified the directive file to make it able to print out the values in textarea, radio, checkbox, select, also it is already able to print the value in the input type=text

Here's the file i modified:

import { Directive, HostListener, Input } from '@angular/core';
@Directive({
  selector: "button[ngxPrint]"
})
export class NgxPrintDirective {

  public _printStyle = [];

  /**
   *
   *
   * @memberof NgxPrintDirective
   */
  @Input() printSectionId: string;

  /**
   *
   *
   * @memberof NgxPrintDirective
   */
  @Input() printTitle: string;

  /**
   *
   *
   * @memberof NgxPrintDirective
   */
  @Input() useExistingCss = false;

  /**
   * A delay in milliseconds to force the print dialog to wait before opened. Default: 0
   *
   * @memberof NgxPrintDirective
   */
  @Input() printDelay: number = 0;

  /**
   *
   *
   * @memberof NgxPrintDirective
   */
  @Input()
  set printStyle(values: { [key: string]: { [key: string]: string } }) {
    for (let key in values) {
      if (values.hasOwnProperty(key)) {
        this._printStyle.push((key + JSON.stringify(values[key])).replace(/['"]+/g, ''));
      }
    }
    this.returnStyleValues();
  }

  /**
   *
   *
   * @returns the string that create the stylesheet which will be injected
   * later within <style></style> tag.
   *
   * -join/replace to transform an array objects to css-styled string
   *
   * @memberof NgxPrintDirective
   */
  public returnStyleValues() {
    return `<style> ${this._printStyle.join(' ').replace(/,/g,';')} </style>`;
  }

  /**
   *
   *
   * @returns html for the given tag
   *
   * @memberof NgxPrintDirective
   */
  private _styleSheetFile = '';

  /**
   * @memberof NgxPrintDirective
   * @param cssList
   */
  @Input()
  set styleSheetFile(cssList: string) {
    let linkTagFn = function(cssFileName) {
      return `<link rel="stylesheet" type="text/css" href="${cssFileName}">`;
    }
    if (cssList.indexOf(',') !== -1) {
      const valueArr = cssList.split(',');
      for (let val of valueArr) {
        this._styleSheetFile = this._styleSheetFile + linkTagFn(val);
      }
    } else {
      this._styleSheetFile = linkTagFn(cssList);
    }
  }

  /**
   * @returns string which contains the link tags containing the css which will
   * be injected later within <head></head> tag.
   *
   */
  private returnStyleSheetLinkTags() {
    return this._styleSheetFile;
  }
  private getElementTag(tag: keyof HTMLElementTagNameMap): string {
    const html: string[] = [];
    const elements = document.getElementsByTagName(tag);
    for (let index = 0; index < elements.length; index++) {
      html.push(elements[index].outerHTML);
    }
    return html.join('\r\n');
  }

  /**
   * @returns html section to be printed along with some associated inputs
   *
   */
  private getHtmlContents() {
    let printContents: any = document.getElementById(this.printSectionId);
    let allInputControls: any = printContents.getElementsByTagName('input');
    let textareaControls: any = printContents.getElementsByTagName('textarea');
    let selectControls: any = printContents.getElementsByTagName('select');
    let radioControls: any = [];
    let checkboxControls: any = [];

    for(let i = 0; i < allInputControls.length; i++) {
      allInputControls[i].defaultValue = allInputControls[i].value;
      if (allInputControls[i].type === 'radio'){
        radioControls.push(allInputControls[i]);
      }

      if (allInputControls[i].type === 'checkbox'){
        checkboxControls.push(allInputControls[i]);
      }
    }

    for(let i = 0; i < textareaControls.length; i++) {
      textareaControls[i].defaultValue = textareaControls[i].value;
    }

    for (let i = 0; i < selectControls.length; i++) {
      const optionsInEachSelect: any = selectControls[i].getElementsByTagName('option');
      for (let j = 0; j < optionsInEachSelect.length; j ++) {
        if (selectControls[i].value.toString() === optionsInEachSelect[j].value.toString()) {
          optionsInEachSelect[j].setAttribute('selected', '');
        } else {
          optionsInEachSelect[j].removeAttribute('selected');
        }
      }
    }

    for (let i = 0; i < radioControls.length; i++) {
        if (radioControls[i].checked === true) {
          radioControls[i].setAttribute('checked', '');
        } else {
          radioControls[i].removeAttribute('checked');
        }
      }

    for (let i = 0; i < checkboxControls.length; i++) {
      if (checkboxControls[i].checked === true) {
        checkboxControls[i].setAttribute('checked', '');
      } else {
        checkboxControls[i].removeAttribute('checked');
      }
    }

    console.log(textareaControls);

    return printContents.innerHTML;
  }

  /**
   *
   *
   * @memberof NgxPrintDirective
   */
  @HostListener('click')
  public print(): void {
    let printContents, popupWin, styles = '', links = '';

    if(this.useExistingCss) {
      styles = this.getElementTag('style');
      links = this.getElementTag('link');
    }

    printContents = this.getHtmlContents();
    popupWin = window.open("", "_blank", "top=0,left=0,height=auto,width=auto");
    popupWin.document.open();
    popupWin.document.write(`
      <html>
        <head>
          <title>${this.printTitle ? this.printTitle : ""}</title>
          ${this.returnStyleValues()}
          ${this.returnStyleSheetLinkTags()}
          ${styles}
          ${links}
        </head>
        <body>
          ${printContents}
          <script defer>
            function triggerPrint(event) {
              window.removeEventListener('load', triggerPrint, false);
              setTimeout(function() {
                window.print();
                setTimeout(function() { window.close(); }, 0);
              }, ${this.printDelay});
            }
            window.addEventListener('load', triggerPrint, false);
          </script>
        </body>
      </html>`);
    //popupWin.document.close();
  }
}

**Comment by sunu-xminds** [comment]
Hi @nisha2107 
Any update regarding this. I am also facing the same problem.

- OS: Ubuntu and iOS
- Browser : Chrome

Thanks in advance

**Comment by nisha2107** [comment]
@sunu-xminds , Currently upgrading my project to Angular 9, so i will be testing print function after that. 
Unable to find any solution with Angular 8.

**Comment by Rodolfo-XDR** [comment]
Any update on this issue? or a temp solution? @nisha2107  @sunu-xminds

**Comment by nisha2107** [comment]
@Rodolfo-XDR @sunu-xminds ,
I am still facing this issue with Angular 8. And no temp solution I found yet. 
Do let us know if you guys get any solution. As the people responsible are not even responding to this issue.

**Comment by zpydee** [comment]
I am experiencing the same issue...

**Comment by vilanekc** [comment]
Same here
- ng 10
- mac
- chrome

**Comment by nisha2107** [comment]
Hi @vilanekc  @zpydee  @Rodolfo-XDR  @sunu-xminds ,

No updates from library.
Looks like reactive forms and useExistingCSS are not supported after version Angular 7. 
I am looking for any other way to implement print in my application. Will update here incase i found any way.

Meanwhile if any one of you gets a solution pls update others. 
Thanks

**Comment by NIKITA-2710** [comment]
I have got same issue . Trying to find an answer .
Hope  @broem  could help us

**Comment by RodolfoXDR** [comment]
Still no answer from OP?

**Comment by broem** [comment]
I have a preliminary fix for this, should be able to get it out this upcoming weekend.

**Comment by broem** [comment]
v1.20 should address these issues
