### ISSUE TITLE
Angula 9 + Electron (latest) + "ngx-print": "^1.2.0-beta.5",

### ISSUE THREAD

**Issue by DanielFrugoni-dev** [selemxmn/ngx-print#88]
**screen shot**
![image](https://user-images.githubusercontent.com/67068799/84928139-4bbca200-b0a4-11ea-84c2-c75df30ed7a6.png)

when click in print button.

Any help ?

**Comment by broem** [comment]
Without more information there's nothing we can do, can you give a small reproducible example of this?

**Comment by Suroor-Ahmmad** [comment]
This is not issue with ngx-print, refer below stackeoverflow answer

Reference: 
https://stackoverflow.com/a/55004890/4336796

**Comment by MatteoFe** [comment]
for future reference:
this is an Electron problem, solution is add nativeWindowOpen: true in main.js as described here:
https://www.electronjs.org/docs/api/window-open
