### ISSUE TITLE
Angular 10 Support

### ISSUE THREAD

**Issue by pavankjadda** [selemxmn/ngx-print#92]
**Is your feature request related to a problem? Please describe.**
No, Support Angular 1o

**Describe the solution you'd like**
Update dependencies to Angular 10 

**Describe alternatives you've considered**
None

**Comment by MubeenTahirCheema** [comment]
This likely means that the library (ngx-printer/lib/ngx-printer.module) which declares NgxPrinterModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by ruslanpascoal2** [comment]
same here

**Comment by ummadi-sreeni** [comment]
> 
> 
> This likely means that the library (ngx-printer/lib/ngx-printer.module) which declares NgxPrinterModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

In this case try restarting your angular server and the problem might be resolved(In my case it worked more than 30 times).
